### ISSUE TITLE
chaosblade-operator  panic because of runtime error: slice bounds out of range [:12] with length 0

### ISSUE THREAD

**Issue by zousheng** [chaosblade-io/chaosblade-operator#141]
## Issue Description

Type: *bug report* or *feature request*
bug report 

### Describe what happened (or what feature you want)

When executing jvm process experiment, panic occurred.

errors:
：time="2022-03-17T13:21:30Z" level=info msg="get pods by names prod-docker-a-dep1-55f4f6597f-jtx8s, len is 1" experiment=h-hs-sirius-01b1647522974062nweewgovov-prod-docker-a-dep1-55f4f6597f-jtx8s

E0317 13:21:30.399143 7 runtime.go:78] Observed a panic: runtime.boundsError{x:12, y:0, signed:true, code:0x1} (runtime error: slice bounds out of range [:12] with length 0)

goroutine 659 [running]:

k8s.io/apimachinery/pkg/util/runtime.logPanic({0x14707c0, 0xc01901f5a8})

/Users/wufan/go/pkg/mod/k8s.io/apimachinery@v0.17.4/pkg/util/runtime/runtime.go:74 +0x99

k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0xc009718400})

### Describe what you expected to happen

       no panic occurs. the containerStatus.ContainerID field should not be empty
       
### How to reproduce it (as minimally and precisely as possible)
   

    This doesn't happen every time, just random occurs.

### Tell us your environment
 k8s: 1.18.9
    container runtime: docker
    run jvm process experiment

### Anything else we need to know?

     When running experiment, pod is in ready state, no restart.

**Comment by zousheng** [comment]
This happens when triggering rate limit, the default qps and burst setting is small

**Comment by oss-sentinel-ai** [comment]
## Issue Evaluation

**Category:** `type/bug` | **Status:** Confirmed

### Root Cause Analysis

The panic `slice bounds out of range [:12] with length 0` is caused by missing bounds checks before truncating container IDs to 12 characters.

**Vulnerable code locations identified:**

1. **`exec/container/controller.go:151`** - Slices `containerId[:12]` after checking if `ContainerID` is empty, but doesn't verify the result is ≥12 chars after prefix stripping
2. **`exec/container/controller.go:235`** - No empty check at all before calling `TruncateContainerObjectMetaUid` and slicing
3. **`exec/pod/controller.go:131`** - Error check happens **after** the slicing operation, and no length validation

**Example of the bug pattern:**
```go
containerRuntime, containerId := model.TruncateContainerObjectMetaUid(containerStatus.ContainerID)
if containerRuntime == container.DockerRuntime {
    containerId = containerId[:12]  // PANIC if len(containerId) < 12
}
```

**Safe pattern (already exists in `exec/model/executor_copy.go:426`):**
```go
if len(containerLongId) > 12 {
    return containerLongId[:12], nil
}
return "", fmt.Errorf("the container %s id is illegal", containerLongId)
```

### Impact

- **Severity:** High - causes operator panic and crash
- **Affected components:** Container and pod experiment execution
- **Trigger conditions:** Empty or malformed `ContainerID` in pod status (e.g., container not fully started, race conditions)

### Recommended Fix

Add bounds checking before all `[:12]` slicing operations:
1. Check for errors **before** using the container ID
2. Validate `len(containerId) >= 12` before slicing
3. Return appropriate error if container ID is too short

---
*Automated evaluation by oss-sentinel-ai*
